### ISSUE TITLE
Recusrive schemas don't work in latest version

### ISSUE THREAD

**Issue by rcano** [sksamuel/avro4s#250]
Trying the example in the README https://github.com/sksamuel/avro4s#recursive-schemas and it doesn't compile.

**Comment by girishkolantra** [comment]
In fact, that example does not work in versions 2.0.0 through 2.0.2. It works in version 1.9.0. I haven't tested 1.9.1 because I couldn't download that particular version

**Comment by rcano** [comment]
The example in 1.9.1 compiles, but gives SO in runtime

**Comment by jeroenr** [comment]
Any update on this? Is this also broken in 2.0.4?

**Comment by sksamuel** [comment]
What about 3.0.x ?

**Comment by IvanStepanov** [comment]
Just checked example from README on 3.0.0-RC3 - compiles fine but StackOverflowError in runtime.

**Comment by leahmcguire** [comment]
I get a StackOverflowError error using version 3.0.1

**Comment by RyanBerti** [comment]
Any movement on this? Just tested with 3.0.4 and got `java.lang.NoSuchMethodError: magnolia.TypeName.typeArguments()Lscala/collection/Seq;` with a derivative of the example in the README. 2.0.4 seems to work.

**Comment by sksamuel** [comment]
No such method is odd, it's like there's a version mismatch somewhere.

**Comment by pvillega** [comment]
So...we hit this bug (or so it seems) with an ADT similar to:

```
sealed trait A
final case class OurInt(v: Int) extends A
final case class B(data: List[A]) extends A
final case class C(data: Map[String, A]) extends A
```
Adding in case it helps finding the issue

**Comment by andreas-schroeder** [comment]
Fixed with #491
