### ISSUE TITLE
java.lang.NoSuchMethodError , scala 2.11 ,<artifactId>avro4s-core_2.11</artifactId>       <version>1.7.0</version>

### ISSUE THREAD

**Issue by hongwei1** [sksamuel/avro4s#137]
object a3 extends App{
  import com.sksamuel.avro4s.AvroSchema
  case class GetBanks(date: String)
  implicit val schemaForGetBanks = SchemaFor[GetBanks]
  val schema = AvroSchema[GetBanks]
  println(schema)
}

I got 

Exception in thread "main" java.lang.NoSuchMethodError: org.apache.avro.Schema$Field.<init>(Ljava/lang/String;Lorg/apache/avro/Schema;Ljava/lang/String;Ljava/lang/Object;)V
	at com.sksamuel.avro4s.SchemaFor$.fieldBuilder(SchemaFor.scala:415)
	at com.sksamuel.avro4s.SchemaFor$.fieldBuilder(SchemaFor.scala:397)
	at code.bankconnectors.a3$$anon$1$$ano$$$$fd815288c81c7bcbf9cc8dc666117e5$$$$on$3$$anonfun$2.apply(payloads.scala:41)
	at code.bankconnectors.a3$$anon$1$$ano$$$$fd815288c81c7bcbf9cc8dc666117e5$$$$on$3$$anonfun$2.apply(payloads.scala:41)
	at shapeless.Lazy$$anon$1.value$lzycompute(lazy.scala:121)
	at shapeless.Lazy$$anon$1.value(lazy.scala:121)

**Comment by hongwei1** [comment]
#116 is also not working for me . Thanks for your work. Wish your reply

**Comment by kristoferB** [comment]
I also get this now and then, which is sometimes due to recursive sealed traits, the need to do a clean, or that the type is needed on the val. You can try:

`implicit val schemaForGetBanks: SchemaFor[GetBanks] = SchemaFor[GetBanks]`

But it depends on your class GetBanks.

**Comment by hongwei1** [comment]
I update the issue, added the GetBanks there

**Comment by constantine2nd** [comment]
We have to downgrade version to 1.6.0 in order to work with Scala version 2.11.8. In other words next set up in POM file cause the issue:
<scala.version>2.11</scala.version>
<scala.compiler>2.11.8</scala.compiler>
 <avro.version>1.6.4</avro.version>

**Comment by constantine2nd** [comment]
I've found the problem. Next art of POM file:
```
<dependency>
        <groupId>net.manub</groupId>
        <artifactId>scalatest-embedded-kafka_${scala.version}</artifactId>
        <version>0.11.0</version>
        <exclusions>
          <exclusion>
            <groupId>org.apache.zookeeper</groupId>
            <artifactId>zookeeper</artifactId>
          </exclusion>
          <exclusion>
            <groupId>log4j</groupId>
            <artifactId>log4j</artifactId>
          </exclusion>
        </exclusions>
        <scope>test</scope>
    </dependency>
```
Use Avro 1.7.7 version but avro4s needs 1.8.1
